version: '3'

services:
  django:
    container_name: django
    build: ./src
    # Задание команды, которую нужно запустить при запуске контейнера для сервиса django
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./src:/usr/study/src/
    # Открытие порта на хостовой машине и перенаправление на порт в контейнере
    environment:
      - POSTGRES_DB=mywebsite
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "8000:8000"
    # Зависимость от другого сервиса
    depends_on:
      - pgdb

  pgdb:
    container_name: pgdb
    # Использование готового образа postgres
    image: postgres
    restart: always
    # Задание переменных окружения для контейнера с postgres
    environment:
      - POSTGRES_DB=mywebsite
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    # Связывание тома с директорией в контейнере для сохранения данных postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data/